name: build docs PDF
on:
  push:
    branches:
    - master
    paths:
    - 'docs/document/content/**'
jobs:
  build:
    name: publish PDF
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'univerone/shardingsphere-doc'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: generate PDF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash .github/scripts/generate-pdf.sh
        
        
